### The Momentum Quality score is based on the Frog-In-The-Pan (FIP) hypthosis which posits that the market under-reacts to gradual positive news. The purpose of the feature is to capture high return stocks that have a continuous and gradual rise. Additional details regarding this theory can be found at https://alphaarchitect.com/2015/11/23/frog-in-the-pan-identifying-the-highest-quality-momentum-stocks/. The FIP quant metric accounts for two factors: 1)price return and 2)path quality (measured by the difference between the percentage of negative and positive days during a period)

### The FIP metric is represented by the following equation:

## ID = +-(stock_return)(%up_days - %down_days)

In [206]:
%matplotlib inline

import requests
import pandas as pd 
import matplotlib.pyplot as plt

START_DATE = '2011-01-03'
END_DATE = '2019-04-03'

In [207]:
file_name = "data/moving-avg-momentum.csv";
output_file = "data/spy-momentum.csv"
df = pd.read_csv(file_name)

In [208]:
df.set_index(['Symbol', 'Date'], inplace=True)

In [209]:
df['Momentum_Quality_Monthly'] = (df['Pct_Change_Monthly'] * 100) * (( df['Rolling_Monthly_Mean_Positive_Days'] - (1 - df['Rolling_Monthly_Mean_Positive_Days'])))
df['Momentum_Quality_Yearly'] = (df['Pct_Change_Yearly'] * 100) * (( df['Rolling_Yearly_Mean_Positive_Days'] - (1 - df['Rolling_Yearly_Mean_Positive_Days'])))

In [210]:
df.head()

                        High        Low       Open      Close     Volume  \
Symbol Date
A      2011-01-03  30.143061  29.620888  29.728184  29.957081  4994000.0
       2011-01-04  30.114449  29.456366  30.035765  29.678112  5017200.0
       2011-01-05  29.849785  29.327610  29.513592  29.613733  4519000.0
       2011-01-06  29.928469  29.477825  29.592276  29.670958  4699000.0
       2011-01-07  29.899857  29.356224  29.699572  29.771101  3810900.0

                    AdjClose  Pct_Change_Daily  Pct_Change_Monthly  \
Symbol Date
A      2011-01-03  27.591616               NaN                 NaN
       2011-01-04  27.334681         -0.009312                 NaN
       2011-01-05  27.275387         -0.002169                 NaN
       2011-01-06  27.328091          0.001932                 NaN
       2011-01-07  27.420322          0.003375                 NaN

                   Pct_Change_Yearly  RSI  Volatility  Yearly_Return_Rank  \
Symbol Date
A      2011-01-03                NaN  NaN         NaN                 NaN
       2011-01-04                NaN  NaN         NaN                 NaN
       2011-01-05                NaN  NaN         NaN                 NaN
       2011-01-06                NaN  NaN         NaN                 NaN
       2011-01-07                NaN  NaN         NaN                 NaN

                   Monthly_Return_Rank  Pct_Change_Class  \
Symbol Date
A      2011-01-03                  NaN               1.0
       2011-01-04                  NaN               0.0
       2011-01-05                  NaN               0.0
       2011-01-06                  NaN               1.0
       2011-01-07                  NaN               1.0

                   Rolling_Yearly_Mean_Positive_Days  \
Symbol Date
A      2011-01-03                                NaN
       2011-01-04                                NaN
       2011-01-05                                NaN
       2011-01-06                                NaN
       2011-01-07                                NaN

                   Rolling_Monthly_Mean_Positive_Days  \
Symbol Date
A      2011-01-03                                 NaN
       2011-01-04                                 NaN
       2011-01-05                                 NaN
       2011-01-06                                 NaN
       2011-01-07                                 NaN

                   Rolling_Monthly_Mean_Price  Rolling_Yearly_Mean_Price  \
Symbol Date
A      2011-01-03                         NaN                        NaN
       2011-01-04                         NaN                        NaN
       2011-01-05                         NaN                        NaN
       2011-01-06                         NaN                        NaN
       2011-01-07                         NaN                        NaN

                   Momentum_Quality_Monthly  Momentum_Quality_Yearly
Symbol Date
A      2011-01-03                       NaN                      NaN
       2011-01-04                       NaN                      NaN
       2011-01-05                       NaN                      NaN
       2011-01-06                       NaN                      NaN
       2011-01-07                       NaN                      NaN

### SPY Trailing Monthly Return Feature is intended to help capture systematic trends in the market.

In [211]:
spy = pd.read_csv("data/spy-price-returns.csv")

In [212]:
spy.drop(columns=['Unnamed: 0'], inplace=True)

In [213]:
#df.groupby(level=0)['SPY_Trailing_Month_Return'] = spy['Pct_Change_Monthly']
spy.set_index('Date', inplace=True)

In [214]:
spy.head()

,Symbol,High,Low,Open,Close,Volume,AdjClose,Pct_Change_Daily,Pct_Change_Monthly,Pct_Change_Yearly
Date,,,,,,,,,,
1/3/11,SPY,127.599998,125.699997,126.709999,127.050003,138725200,107.598145,NaN,NaN,NaN
1/4/11,SPY,127.370003,126.190002,127.330002,126.980003,137409700,107.538879,-0.000551,NaN,NaN
1/5/11,SPY,127.720001,126.459999,126.580002,127.639999,133975300,108.097839,0.005198,NaN,NaN
1/6/11,SPY,127.830002,127.010002,127.690002,127.389999,122519000,107.886108,-0.001959,NaN,NaN
1/7/11,SPY,127.769997,126.150002,127.559998,127.139999,156034600,107.674393,-0.001962,NaN,NaN

In [215]:
spy_trailing_month_return = spy.drop(columns=['Symbol', 'High', 'Low', 'Open', 'Close', 'Volume', 'AdjClose', 'Pct_Change_Daily', 'Pct_Change_Yearly'])

In [216]:
global spy_df
spy_df = pd.DataFrame()
spy_trailing_month_return['SPY_Trailing_Month_Return'] = spy_trailing_month_return['Pct_Change_Monthly']
spy_trailing_month_return.drop(columns=['Pct_Change_Monthly'], inplace=True)

In [217]:
spy_trailing_month_return.reset_index(inplace=True)
spy_trailing_month_return.drop(columns=['Date'], inplace=True)

for symbol, r in df.groupby(level=0):
    tmp = r
    tmp.reset_index(inplace=True)
    tick = pd.merge(tmp, spy_trailing_month_return, how='left', left_index=True, right_index=True)
    spy_df = spy_df.append(tick)

In [218]:
spy_df.set_index(['Symbol', 'Date'], inplace=True)

In [219]:
spy_df.to_csv(output_file, encoding='utf-8', index=True)